-- Voorraad, inkooporders en leveranciers (dashboard).
-- Alleen toevoegen, idempotent. De code werkt ook zonder deze migratie, dan
-- vallen de nieuwe onderdelen terug op het oude gedrag.
--
-- Let op foreign keys: geen enkele tabel krijgt hier een tweede FK naar een
-- tabel waar hij al naar verwijst. inkoopregels -> leveranciers bestaat al;
-- de nieuwe FK op inkoopregels gaat naar inkooporders, een andere tabel.

-- 1. Voorraadartikel ja/nee --------------------------------------------------
-- Standaard nee: het meeste wordt op order besteld en hoort niet als "0 op
-- voorraad" in de lijst. Op de variant is null = volgt het product.
alter table public.producten add column if not exists voorraad_bijhouden boolean not null default false;
alter table public.product_varianten add column if not exists voorraad_bijhouden boolean;
-- Minimum per variant (maat/kleur). producten.min_voorraad blijft het totaal.
alter table public.product_varianten add column if not exists min_voorraad integer;
-- Vrije locatie (schap, magazijn, bus) voor de telling per locatie.
alter table public.product_varianten add column if not exists locatie text;

-- 2. Voorraadmutaties ---------------------------------------------------------
create table if not exists public.voorraad_mutaties (
  id uuid primary key default gen_random_uuid(),
  variant_id uuid references public.product_varianten(id) on delete cascade,
  product_id uuid references public.producten(id) on delete set null,
  veld text not null default 'voorraad' check (veld in ('voorraad', 'min_voorraad')),
  soort text not null check (soort in ('telling', 'ontvangst', 'correctie', 'retour', 'verkoop', 'instelling')),
  oud integer,
  nieuw integer,
  verschil integer,
  notitie text,
  -- Bewust zonder FK: alleen ter verwijzing.
  inkoopregel_id uuid,
  actor text,
  created_at timestamptz not null default now()
);
create index if not exists voorraad_mutaties_variant_idx on public.voorraad_mutaties (variant_id, created_at desc);
alter table public.voorraad_mutaties enable row level security;

-- 3. Inkooporders -------------------------------------------------------------
create table if not exists public.inkooporders (
  id uuid primary key default gen_random_uuid(),
  nummer integer generated by default as identity,
  -- Eén van de merkrijen van de inkooppartij, voor de link naar de leverancier.
  leverancier_id uuid references public.leveranciers(id) on delete set null,
  -- De handelspartij waar in één keer besteld wordt (leveranciers.inkoop_bij).
  inkoop_partij text,
  status text not null default 'concept'
    check (status in ('concept', 'verstuurd', 'deels_ontvangen', 'ontvangen', 'geannuleerd')),
  besteld_op date,
  verwacht_op date,
  ontvangen_op date,
  referentie text,
  notitie text,
  verstuurd_per text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists inkooporders_status_idx on public.inkooporders (status);
create index if not exists inkooporders_leverancier_idx on public.inkooporders (leverancier_id);
alter table public.inkooporders enable row level security;

-- De bestaande inkoopregels worden de regels van een inkooporder.
alter table public.inkoopregels add column if not exists inkooporder_id uuid references public.inkooporders(id) on delete set null;
alter table public.inkoopregels add column if not exists inkoopprijs numeric;
alter table public.inkoopregels add column if not exists ontvangen_op date;
-- 'order' (tekort op klantorder), 'bijbestellen' (onder minimum) of 'handmatig'.
alter table public.inkoopregels add column if not exists bron text;
create index if not exists inkoopregels_inkooporder_idx on public.inkoopregels (inkooporder_id);
create index if not exists inkoopregels_status_idx on public.inkoopregels (status);

-- 4. Leveranciers -------------------------------------------------------------
alter table public.leveranciers add column if not exists website text;
alter table public.leveranciers add column if not exists logo_url text;
alter table public.leveranciers add column if not exists klantnummer text;
alter table public.leveranciers add column if not exists franco_bedrag numeric;
alter table public.leveranciers add column if not exists notities text;
-- [{ "naam": "Prijslijst 2026", "url": "https://..." }]
alter table public.leveranciers add column if not exists documenten jsonb not null default '[]'::jsonb;

create table if not exists public.leverancier_contacten (
  id uuid primary key default gen_random_uuid(),
  leverancier_id uuid not null references public.leveranciers(id) on delete cascade,
  naam text not null,
  rol text,
  email text,
  telefoon text,
  notitie text,
  created_at timestamptz not null default now()
);
create index if not exists leverancier_contacten_lev_idx on public.leverancier_contacten (leverancier_id);
alter table public.leverancier_contacten enable row level security;

notify pgrst, 'reload schema';
